type: api
method: POST
url: http://localhost:8090/ingest_text
data:
  domain: handey
  session_id: H500
  channel: imagery
  text: "The candle lectured the sun, but its wax confessed the dark. Then the river laughed and carried the lesson downstream."
